name: Sync to Upstream
# keep all forked repo synck with original repo
on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: master # main branch
    
    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
        upstream_repository: MallikarjunHt/Hacktoberfest2020-HTML-CSS-WEB #your repo
        upstream_branch: master #your main branch
        target_branch: master                       # optional
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that requir authentication
        
    # Step 3: Print a helpful timestamp for your records (optional)
    - name: Timestamp
      run: date
